climate_works_dbt:
  target: cw_md_prod
  outputs:
    cw_dev:
      type: duckdb
      database: dev_database
      schema: dev_sode
      path: './dev_database.duckdb'
    cw_md_dev:
      type: duckdb
      schema: dev_sode
      path: "md:climate_works?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
    cw_md_prod:
      type: duckdb
      schema: prod_sode
      path: "md:climate_works?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"